from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(425, 280))
        MainWindow.setMaximumSize(QtCore.QSize(425, 280))
        MainWindow.setBaseSize(QtCore.QSize(425, 280))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setWindowOpacity(0.9)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.centralwidget.setFont(font)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.INJECT = QtWidgets.QPushButton(self.centralwidget)
        self.INJECT.setGeometry(QtCore.QRect(10, 10, 130, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.INJECT.sizePolicy().hasHeightForWidth())
        self.INJECT.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.INJECT.setFont(font)
        self.INJECT.setMouseTracking(True)
        self.INJECT.setToolTipDuration(5)
        self.INJECT.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(245, 245, 245);")
        self.INJECT.setObjectName("INJECT")
        self.Speed = QtWidgets.QSpinBox(self.centralwidget)
        self.Speed.setGeometry(QtCore.QRect(10, 50, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Speed.setFont(font)
        self.Speed.setMouseTracking(True)
        self.Speed.setToolTipDuration(3)
        self.Speed.setAutoFillBackground(False)
        self.Speed.setStyleSheet("color: rgb(245, 245, 245);")
        self.Speed.setAlignment(QtCore.Qt.AlignCenter)
        self.Speed.setMinimum(-1000)
        self.Speed.setMaximum(1000)
        self.Speed.setProperty("value", 25)
        self.Speed.setProperty("clearButtonEnabled", True)
        self.Speed.setObjectName("Speed")
        self.Jumppower = QtWidgets.QSpinBox(self.centralwidget)
        self.Jumppower.setGeometry(QtCore.QRect(150, 50, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Jumppower.setFont(font)
        self.Jumppower.setMouseTracking(True)
        self.Jumppower.setToolTipDuration(3)
        self.Jumppower.setAutoFillBackground(False)
        self.Jumppower.setStyleSheet("color: rgb(245, 245, 245);")
        self.Jumppower.setAlignment(QtCore.Qt.AlignCenter)
        self.Jumppower.setMinimum(-1000)
        self.Jumppower.setMaximum(1000)
        self.Jumppower.setProperty("value", 70)
        self.Jumppower.setProperty("clearButtonEnabled", True)
        self.Jumppower.setObjectName("Jumppower")
        self.FOV = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.FOV.setGeometry(QtCore.QRect(290, 50, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FOV.setFont(font)
        self.FOV.setMouseTracking(True)
        self.FOV.setToolTipDuration(3)
        self.FOV.setAutoFillBackground(False)
        self.FOV.setStyleSheet("color: rgb(245, 245, 245);")
        self.FOV.setAlignment(QtCore.Qt.AlignCenter)
        self.FOV.setMinimum(1.0)
        self.FOV.setMaximum(2.0)
        self.FOV.setSingleStep(0.05)
        self.FOV.setProperty("value", 1.5)
        self.FOV.setProperty("clearButtonEnabled", True)
        self.FOV.setObjectName("FOV")
        self.LoopSetFOV = QtWidgets.QCheckBox(self.centralwidget)
        self.LoopSetFOV.setGeometry(QtCore.QRect(290, 90, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LoopSetFOV.setFont(font)
        self.LoopSetFOV.setMouseTracking(True)
        self.LoopSetFOV.setToolTipDuration(5)
        self.LoopSetFOV.setStyleSheet("color: rgb(245, 245, 245)")
        self.LoopSetFOV.setIconSize(QtCore.QSize(20, 20))
        self.LoopSetFOV.setChecked(False)
        self.LoopSetFOV.setObjectName("LoopSetFOV")
        self.AfterDeathApply = QtWidgets.QCheckBox(self.centralwidget)
        self.AfterDeathApply.setGeometry(QtCore.QRect(150, 90, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.AfterDeathApply.setFont(font)
        self.AfterDeathApply.setMouseTracking(True)
        self.AfterDeathApply.setToolTipDuration(5)
        self.AfterDeathApply.setStyleSheet("color: rgb(245, 245, 245);")
        self.AfterDeathApply.setIconSize(QtCore.QSize(20, 20))
        self.AfterDeathApply.setChecked(False)
        self.AfterDeathApply.setObjectName("AfterDeathApply")
        self.DelFog = QtWidgets.QPushButton(self.centralwidget)
        self.DelFog.setGeometry(QtCore.QRect(290, 10, 130, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DelFog.sizePolicy().hasHeightForWidth())
        self.DelFog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.DelFog.setFont(font)
        self.DelFog.setMouseTracking(True)
        self.DelFog.setToolTipDuration(2)
        self.DelFog.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(245, 245, 245);")
        self.DelFog.setObjectName("DelFog")
        self.Gravity = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Gravity.setGeometry(QtCore.QRect(10, 90, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Gravity.setFont(font)
        self.Gravity.setMouseTracking(True)
        self.Gravity.setToolTipDuration(3)
        self.Gravity.setAutoFillBackground(False)
        self.Gravity.setStyleSheet("color: rgb(245, 245, 245);")
        self.Gravity.setAlignment(QtCore.Qt.AlignCenter)
        self.Gravity.setMinimum(-1000.0)
        self.Gravity.setMaximum(1000.0)
        self.Gravity.setSingleStep(1.0)
        self.Gravity.setProperty("value", 196.2)
        self.Gravity.setProperty("clearButtonEnabled", True)
        self.Gravity.setObjectName("Gravity")
        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        self.Reset.setGeometry(QtCore.QRect(150, 10, 130, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reset.sizePolicy().hasHeightForWidth())
        self.Reset.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Reset.setFont(font)
        self.Reset.setMouseTracking(True)
        self.Reset.setToolTipDuration(3)
        self.Reset.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(245, 245, 245);")
        self.Reset.setObjectName("Reset")
        self.Noclip = QtWidgets.QCheckBox(self.centralwidget)
        self.Noclip.setGeometry(QtCore.QRect(10, 130, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Noclip.setFont(font)
        self.Noclip.setMouseTracking(True)
        self.Noclip.setToolTipDuration(5)
        self.Noclip.setStyleSheet("color: rgb(245, 245, 245)")
        self.Noclip.setIconSize(QtCore.QSize(20, 20))
        self.Noclip.setChecked(False)
        self.Noclip.setObjectName("Noclip")
        self.Radar = QtWidgets.QCheckBox(self.centralwidget)
        self.Radar.setGeometry(QtCore.QRect(10, 180, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Radar.setFont(font)
        self.Radar.setMouseTracking(True)
        self.Radar.setToolTipDuration(5)
        self.Radar.setStyleSheet("color: rgb(245, 245, 245)")
        self.Radar.setIconSize(QtCore.QSize(20, 20))
        self.Radar.setChecked(False)
        self.Radar.setObjectName("Radar")
        self.IgnoreTeamRadar = QtWidgets.QCheckBox(self.centralwidget)
        self.IgnoreTeamRadar.setGeometry(QtCore.QRect(150, 180, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IgnoreTeamRadar.setFont(font)
        self.IgnoreTeamRadar.setMouseTracking(True)
        self.IgnoreTeamRadar.setToolTipDuration(5)
        self.IgnoreTeamRadar.setStyleSheet("color: rgb(245, 245, 245)")
        self.IgnoreTeamRadar.setIconSize(QtCore.QSize(20, 20))
        self.IgnoreTeamRadar.setChecked(False)
        self.IgnoreTeamRadar.setObjectName("IgnoreTeamRadar")
        self.IgnoreDeadRadar = QtWidgets.QCheckBox(self.centralwidget)
        self.IgnoreDeadRadar.setGeometry(QtCore.QRect(290, 180, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IgnoreDeadRadar.setFont(font)
        self.IgnoreDeadRadar.setMouseTracking(True)
        self.IgnoreDeadRadar.setToolTipDuration(5)
        self.IgnoreDeadRadar.setStyleSheet("color: rgb(245, 245, 245)")
        self.IgnoreDeadRadar.setIconSize(QtCore.QSize(20, 20))
        self.IgnoreDeadRadar.setChecked(False)
        self.IgnoreDeadRadar.setObjectName("IgnoreDeadRadar")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 170, 411, 2))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line.setFont(font)
        self.line.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 220, 411, 2))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ESP = QtWidgets.QCheckBox(self.centralwidget)
        self.ESP.setGeometry(QtCore.QRect(10, 230, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ESP.setFont(font)
        self.ESP.setMouseTracking(True)
        self.ESP.setToolTipDuration(5)
        self.ESP.setStyleSheet("color: rgb(245, 245, 245)")
        self.ESP.setIconSize(QtCore.QSize(20, 20))
        self.ESP.setChecked(False)
        self.ESP.setObjectName("ESP")
        self.IgnoreTeamEsp = QtWidgets.QCheckBox(self.centralwidget)
        self.IgnoreTeamEsp.setGeometry(QtCore.QRect(150, 230, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IgnoreTeamEsp.setFont(font)
        self.IgnoreTeamEsp.setMouseTracking(True)
        self.IgnoreTeamEsp.setToolTipDuration(5)
        self.IgnoreTeamEsp.setStyleSheet("color: rgb(245, 245, 245)")
        self.IgnoreTeamEsp.setIconSize(QtCore.QSize(20, 20))
        self.IgnoreTeamEsp.setChecked(False)
        self.IgnoreTeamEsp.setObjectName("IgnoreTeamEsp")
        self.IgnoreDeadEsp = QtWidgets.QCheckBox(self.centralwidget)
        self.IgnoreDeadEsp.setGeometry(QtCore.QRect(290, 230, 130, 35))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IgnoreDeadEsp.setFont(font)
        self.IgnoreDeadEsp.setMouseTracking(True)
        self.IgnoreDeadEsp.setToolTipDuration(5)
        self.IgnoreDeadEsp.setStyleSheet("color: rgb(245, 245, 245)")
        self.IgnoreDeadEsp.setIconSize(QtCore.QSize(20, 20))
        self.IgnoreDeadEsp.setChecked(False)
        self.IgnoreDeadEsp.setObjectName("IgnoreDeadEsp")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RobloHck 3000"))
        self.INJECT.setToolTip(_translate("MainWindow", "Press it before using cheat and after joining game"))
        self.INJECT.setText(_translate("MainWindow", "INJECT"))
        self.Speed.setToolTip(_translate("MainWindow", "Changes your speed"))
        self.Speed.setProperty("text", _translate("MainWindow", "25"))
        self.Speed.setProperty("placeholderText", _translate("MainWindow", "Speed"))
        self.Jumppower.setToolTip(_translate("MainWindow", "How high you jump"))
        self.Jumppower.setProperty("text", _translate("MainWindow", "70"))
        self.Jumppower.setProperty("placeholderText", _translate("MainWindow", "Jump power"))
        self.FOV.setToolTip(_translate("MainWindow", "Field of view"))
        self.FOV.setProperty("text", _translate("MainWindow", "1.50"))
        self.FOV.setProperty("placeholderText", _translate("MainWindow", "FOV"))
        self.LoopSetFOV.setToolTip(_translate("MainWindow", "If game always resets your FOV, you can use it!"))
        self.LoopSetFOV.setText(_translate("MainWindow", "Loop set FOV"))
        self.AfterDeathApply.setToolTip(_translate("MainWindow", "Roblox can crash!!!"))
        self.AfterDeathApply.setText(_translate("MainWindow", "After death\n"
"apply"))
        self.DelFog.setToolTip(_translate("MainWindow", "Deletes fog"))
        self.DelFog.setText(_translate("MainWindow", "Remove fog"))
        self.Gravity.setToolTip(_translate("MainWindow", "Gravity"))
        self.Gravity.setProperty("text", _translate("MainWindow", "196.20"))
        self.Gravity.setProperty("placeholderText", _translate("MainWindow", "Gravity"))
        self.Reset.setToolTip(_translate("MainWindow", "Resets character"))
        self.Reset.setText(_translate("MainWindow", "Reset"))
        self.Noclip.setToolTip(_translate("MainWindow", "Makes you able go through walls"))
        self.Noclip.setText(_translate("MainWindow", "Noclip"))
        self.Radar.setToolTip(_translate("MainWindow", "Adds radar to corner of your screen"))
        self.Radar.setText(_translate("MainWindow", "Radar"))
        self.IgnoreTeamRadar.setToolTip(_translate("MainWindow", "Radar will ignore your team if you enable this"))
        self.IgnoreTeamRadar.setText(_translate("MainWindow", "Ignore your\n"
"team"))
        self.IgnoreDeadRadar.setToolTip(_translate("MainWindow", "Radar will ignore your dead players if you enable this"))
        self.IgnoreDeadRadar.setText(_translate("MainWindow", "Ignore dead"))
        self.ESP.setToolTip(_translate("MainWindow", "Adds radar to corner of your screen"))
        self.ESP.setText(_translate("MainWindow", "Esp"))
        self.IgnoreTeamEsp.setToolTip(_translate("MainWindow", "Radar will ignore your team if you enable this"))
        self.IgnoreTeamEsp.setText(_translate("MainWindow", "Ignore your\n"
"team"))
        self.IgnoreDeadEsp.setToolTip(_translate("MainWindow", "Radar will ignore your dead players if you enable this"))
        self.IgnoreDeadEsp.setText(_translate("MainWindow", "Ignore dead"))
